########################################
# Basic Configuration
########################################
theme_version_check: true
theme_config_check: true
# main menu navigation
# 站点导航：只保留首页 / 归档 / 关于
# for more icon information, please visit https://github.com/D-Sketon/hexo-theme-reimu/issues/30
menu:
  - name: home
    url: /
    icon: # default use taichi icon, you can use a hexadecimal representation of fontawesome or icon_font, like 'f0c1'
  - name: archives
    url: /archives
    icon:
  - name: about
    url: /about
    icon:

subtitle:
  typing:
    enable: false
    strings:
      # - Sentence 1
      # - Sentence 2
      # - Sentence 3
      # - Sentence 4
    typeSpeed: 100 # typing speed (milliseconds/character)
    backSpeed: 50 # backspacing speed (milliseconds/character)
    backDelay: 2000 # time before backspacing (milliseconds)
    startDelay: 300 # time before typing starts (milliseconds)
    loop: true # loop through the strings
    shuffle: true # randomize the order of strings
    showCursor: true # show the typing cursor
    cursorChar: "|" # character for cursor
    smartBackspace: false # only backspace what doesn't match the previous string

banner: "/images/banner.webp" # which means themes/reimu/source/images/banner.webp
# You can also write it in the form of the following url
# banner: "https://example.com"

# If you want to use the srcset attribute, please enable it
banner_srcset:
  enable: false
  srcset:
    - src: "/images/banner-600w.webp"
      media: "(max-width: 479px)"
    - src: "/images/banner-800w.webp"
      media: "(max-width: 799px)"
    - src: "/images/banner.webp"
      media: "(min-width: 800px)"

# 浏览器标签页图标：使用站点资源中的 reimu.png
favicon: "/images/reimu.png" # which means source/images/reimu.png
# You can also write it in the form of the following url
# favicon: "https://example.com"

avatar: "avatar.png" # which means source/_data/avatar/avatar.png

# Control the display of the post cover
# If not set, the banner image will be displayed by default
# Its priority is lower than the cover in the Front-matter
cover: # https://example.com / false / rgb(255,117,117)

# Control the display of the post toc
# Its priority is lower than the toc in the Front-matter
toc: true
toc_options:
  list_number: true
  min_depth: 1
  max_depth: 6

# Open Graph
# see https://hexo.io/docs/helpers#open-graph
open_graph:
  enable: true
  options:
    #twitter_card: <twitter:card>
    #twitter_id: <twitter:creator>
    #twitter_site: <twitter:site>
    #twitter_image: <twitter:image>
    #google_plus: <g+:profile_link>
    #fb_admins: <fb:admin_id>
    #fb_app_id: <fb:app_id>
    default_og_image: /images/banner.webp # the default og:image for Open Graph, support absolute path

# Content
excerpt_link: Read More

# RSS
# need https://github.com/hexojs/hexo-generator-feed
rss: atom.xml

# Footer copyright
copyright: # Inject code snippet right in the footer copyright
# Need help choosing? Please see...
# https://creativecommons.org/choose/
# https://choosealicense.com/
# copyright: |-
#   <div style="flex-direction:column;align-items: center;"><a rel="license" href="http://creativecommons.org/licenses/by/4.0/"><img alt="Creative Commons License" style="border-width:0" src="https://i.creativecommons.org/l/by/4.0/88x31.png" /></a>
#   All website licensed under <a href="https://creativecommons.org/licenses/by/4.0/" target="_blank">CC BY 4.0</a></div>

footer:
  since: 2020 # 2020-current year
  powered: true
  count: true # show word count and reading time
  busuanzi: true
  icon:
    url: "../images/taichi.png" # this path is relative to the css/style.css, so it needs to go up one level to reach the images folder
    rotate: true
    mask: true # whether to use the images as a mask

# Sidebar
# sidebar: right # deprecated, use sidebar.position instead
sidebar:
  position: right
  menu: true # whether to show the sidebar menu button, ignored on mobile devices
  article:
    show_common: true # whether to show common sidebar, ignored on mobile devices

social:
  # email: mailto:xxx@gmail.com
  github: https://github.com/alicesainta-sketch
  # google: https://plus.google.com/yourname
  twitter: https://twitter.com/AliceSaint5883
  # facebook: https://www.facebook.com/yourname
  # instagram: https://www.instagram.com/yourname
  # linkedin: https://www.linkedin.com/in/yourname
  # pinterest: https://www.pinterest.com/yourname
  # youtube: https://www.youtube.com/channel/yourname
  # vimeo: https://vimeo.com/yourname
  # flickr: https://www.flickr.com/photos/yourname
  # dribbble: https://dribbble.com/yourname
  # behance: https://www.behance.net/yourname
  bilibili: https://space.bilibili.com/524327153
  # weibo: https://weibo.com/yourname
  # zhihu: https://www.zhihu.com/people/yourname
  # reddit: https://www.reddit.com/user/yourname
  # tumblr: https://yourname.tumblr.com
  # medium: https://medium.com/@yourname
  # deviantart: https://yourname.deviantart.com
  # stackoverflow: https://stackoverflow.com/users/yourname
  # keybase: https://keybase.io/yourname
  # telegram: https://t.me/yourname
  discord: https://discord.gg/frQShpVN
  # steam: https://steamcommunity.com/id/yourname

widgets:
  # - category
  # - tag
  # - tagcloud
  # - archive
  # - recent_posts

# Widget behavior
archive_type: "monthly"
show_count: false
tag_limits:
recent_posts_limits: 5
tagcloud_limits:

# Archive behavior
only_show_capsule_in_index: false # If you have hugo amounts of tags and categories, you can set this to true to only show the capsule in the index page for better performance
uppercase_capsule: true # If you want to keep taxonomic capsule unchanged, please set this to false

show_update_time: false # If you want to show the update time, please set this to true

# Summary content
summary:
  enable: false
  style: "subtitle" # 'subtitle' or 'blockquote'

# Internationalization
i18n:
  enable: false
  type: [page, post]
  generator: [archive, category, tag, index]
  languages: [zh-CN, en]

########################################
# CSS
########################################

triangle_badge:
  enable: false
  icon: github # same as the icon in the social config
  link: https://github.com/D-Sketon/hexo-theme-reimu

layout:
  max_width: 1350px # the max width of the main content area

anchor_icon: # default use '#' icon, you can use a hexadecimal representation of fontawesome or icon_font, like 'f0c1', or you can use false to hide anchor icon

reimu_cursor:
  enable: true
  cursor:
    default: ../images/cursor/reimu-cursor-default.png # this path is relative to the css/style.css, so it needs to go up one level to reach the images folder
    pointer: ../images/cursor/reimu-cursor-pointer.png
    text: ../images/cursor/reimu-cursor-text.png

# set to false to enable fontawesome
icon_font: 4552607_4k4bc36ef96

# Font loading strategy
# Custom Font -> Google Fonts -> Local FallBack Font

# Custom Font
custom_font:
  enable: false
  article:
    # - css: https://fontsapi.zeoseven.com/292/main/result.css
    # name: LXGW WenKai
  code:

# https://fonts.google.com/
# Google Fonts, higher priority than local_font
font:
  enable: true
  article:
    - Mulish
    - Noto Serif SC
  code:
    # - Ubuntu Mono
    # - Source Code Pro
    # - JetBrains Mono

# Local FallBack Font
local_font:
  article:
    - "-apple-system"
    - PingFang SC
    - Microsoft YaHei
    - sans-serif
  code:
    - Menlo
    - Monaco
    - Consolas
    - monospace

dark_mode:
  enable: false
